Using previously generated data (Notebook 10) to calculate thrombolysis and outcome

In [1]:
import pandas as pd
import numpy as np
import random as rn
import matplotlib.pyplot as plt

In [2]:
num_samples=10000

In [3]:
col_name={
    "Mild Stroke":"stroke_severity_mild",
    "Moderate Stroke":"stroke_severity_moderate",
    "Severe Stroke":"stroke_severity_severe",
    "Age":"age_80plus",
    "Utility":"prior_util",
    "AF_patients":"atrial_fibrillation",
    "AF_patients_on_anticoagulants":"afib_anticoagulant",
    "Onset_during_sleep":"onset_during_sleep",
    "Precise_onset_known":"precise_onset_known",
    "Arrival to scan time":"arrival_to_scan_time"}
df_data=pd.read_csv("final_10_08.csv", index_col=0)
df_data=df_data.rename(columns=col_name)
df_data

,Stroke severity,stroke_severity_mild,stroke_severity_moderate,stroke_severity_severe,age_80plus,MRS,x_values,prior_util,atrial_fibrillation,afib_anticoagulant,onset_during_sleep,precise_onset_known,Stroke team,arrival_to_scan_time
0,5.0,0.0,1.0,0.0,0,0,0.37454,0.95,0,0,0,1,64,41
1,25.0,0.0,1.0,0.0,1,4,0.95071,0.42,1,1,0,0,42,15
2,13.0,0.0,1.0,0.0,1,3,0.73199,0.62,0,0,0,0,12,35
3,9.0,0.0,1.0,0.0,0,0,0.59866,0.95,0,0,0,1,5,87
4,3.0,1.0,0.0,0.0,0,0,0.15602,0.95,0,0,0,1,79,274
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,16.0,0.0,1.0,0.0,1,3,0.85766,0.62,1,0,0,1,63,14
9996,21.0,0.0,1.0,0.0,1,4,0.89751,0.42,1,1,0,1,47,35
9997,25.0,0.0,1.0,0.0,1,4,0.94671,0.42,1,0,0,1,95,23
9998,6.0,0.0,1.0,0.0,0,0,0.39749,0.95,0,0,0,1,26,134
9999,4.0,1.0,0.0,0.0,0,0,0.21714,0.95,0,0,0,1,27,11

In [4]:
# Make one-hot-encoded data:
df_data_ohe = pd.get_dummies(df_data["Stroke team"]).astype(int)
# Merge this into the rest of the iris data:
df_data = pd.concat((df_data, df_data_ohe), axis='columns')
df_data

,Stroke severity,stroke_severity_mild,stroke_severity_moderate,stroke_severity_severe,age_80plus,MRS,x_values,prior_util,atrial_fibrillation,afib_anticoagulant,...,106,107,108,109,110,111,112,113,114,115
0,5.0,0.0,1.0,0.0,0,0,0.37454,0.95,0,0,...,0,0,0,0,0,0,0,0,0,0
1,25.0,0.0,1.0,0.0,1,4,0.95071,0.42,1,1,...,0,0,0,0,0,0,0,0,0,0
2,13.0,0.0,1.0,0.0,1,3,0.73199,0.62,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9.0,0.0,1.0,0.0,0,0,0.59866,0.95,0,0,...,0,0,0,0,0,0,0,0,0,0
4,3.0,1.0,0.0,0.0,0,0,0.15602,0.95,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,16.0,0.0,1.0,0.0,1,3,0.85766,0.62,1,0,...,0,0,0,0,0,0,0,0,0,0
9996,21.0,0.0,1.0,0.0,1,4,0.89751,0.42,1,1,...,0,0,0,0,0,0,0,0,0,0
9997,25.0,0.0,1.0,0.0,1,4,0.94671,0.42,1,0,...,0,0,0,0,0,0,0,0,0,0
9998,6.0,0.0,1.0,0.0,0,0,0.39749,0.95,0,0,...,0,0,0,0,0,0,0,0,0,0
9999,4.0,1.0,0.0,0.0,0,0,0.21714,0.95,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
df_file=pd.read_csv("effects_linreg_allpatients_mrsleq2.csv", index_col=0)
df_file=df_file.fillna(0)
df_file

,precise_onset_known,afib_anticoagulant,prior_util,arrival_to_scan_time,thrombolysis,discharge_util,discharge_mrsleq2
onset_during_sleep,-0.65821,0.00000,0.00000,0.00000,-0.12155,0.00000,0.00000
precise_onset_known,0.00000,0.00000,0.00000,0.00000,0.13737,0.00000,0.00000
atrial_fibrillation,0.00000,0.63438,0.00000,0.00000,0.00000,-0.02679,-0.02420
afib_anticoagulant,0.00000,0.00000,0.00000,0.00000,-0.29834,0.00000,0.00000
prior_util,0.00000,0.00000,0.00000,0.00000,0.32325,0.55124,0.77955
...,...,...,...,...,...,...,...
108,0.00000,0.00000,0.00000,-6.27410,0.03744,-0.02121,-0.03315
thrombolysis,0.00000,0.00000,0.00000,0.00000,0.00000,0.08027,0.10451
discharge_util,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000
discharge_mrsleq2,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000
const,0.65851,0.04014,0.89629,37.83822,0.01126,0.18726,-0.15301

In [6]:
stroke_team_names = df_file.index[df_file.index.str.isnumeric()].values
stroke_team_names

<StringArray>
[  '2',   '3',   '5',   '6',   '7',   '8',   '9',  '11',  '12',  '13',  '14',
  '18',  '20',  '21',  '24',  '25',  '28',  '29',  '31',  '32',  '33',  '34',
  '36',  '38',  '39',  '40',  '42',  '43',  '45',  '47',  '48',  '49',  '51',
  '55',  '56',  '58',  '60',  '61',  '62',  '65',  '66',  '68',  '70',  '71',
  '72',  '73',  '74',  '76',  '77',  '78',  '80',  '82',  '83',  '85',  '87',
  '93',  '94',  '95',  '98',  '99', '100', '103', '104', '106', '107', '108']
Length: 66, dtype: str

In [7]:
df_data=df_data.rename(columns=dict(zip([int(t) for t in stroke_team_names], stroke_team_names)))

In [8]:
df_data=df_data[(df_data[stroke_team_names] == 1).any(axis="columns")]
df_data

,Stroke severity,stroke_severity_mild,stroke_severity_moderate,stroke_severity_severe,age_80plus,MRS,x_values,prior_util,atrial_fibrillation,afib_anticoagulant,...,106,107,108,109,110,111,112,113,114,115
1,25.0,0.0,1.0,0.0,1,4,0.95071,0.42,1,1,...,0,0,0,0,0,0,0,0,0,0
2,13.0,0.0,1.0,0.0,1,3,0.73199,0.62,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9.0,0.0,1.0,0.0,0,0,0.59866,0.95,0,0,...,0,0,0,0,0,0,0,0,0,0
6,2.0,1.0,0.0,0.0,0,0,0.05808,0.95,0,0,...,0,0,0,0,0,0,0,0,0,0
10,2.0,1.0,0.0,0.0,0,0,0.02058,0.95,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,0.0,1.0,0.0,0.0,0,0,0.47111,0.95,0,0,...,0,0,0,0,0,0,0,0,0,0
9993,15.0,0.0,1.0,0.0,1,3,0.81874,0.62,1,0,...,0,0,0,0,0,0,0,0,0,0
9994,3.0,1.0,0.0,0.0,0,0,0.12461,0.95,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,21.0,0.0,1.0,0.0,1,4,0.89751,0.42,1,1,...,0,0,0,0,0,0,0,0,0,0
9997,25.0,0.0,1.0,0.0,1,4,0.94671,0.42,1,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
patients=len(df_data)
patients

5403

In [10]:
data_columns=df_data.columns
data_columns

Index([         'Stroke severity',     'stroke_severity_mild',
       'stroke_severity_moderate',   'stroke_severity_severe',
                     'age_80plus',                      'MRS',
                       'x_values',               'prior_util',
            'atrial_fibrillation',       'afib_anticoagulant',
       ...
                            '106',                      '107',
                            '108',                        109,
                              110,                        111,
                              112,                        113,
                              114,                        115],
      dtype='object', length=129)

In [11]:
file_columns=df_file.index
file_columns

Index(['onset_during_sleep', 'precise_onset_known', 'atrial_fibrillation',
       'afib_anticoagulant', 'prior_util', 'age_80plus',
       'stroke_severity_mild', 'stroke_severity_moderate',
       'stroke_severity_severe', 'arrival_to_scan_time', '2', '3', '5', '6',
       '7', '8', '9', '11', '12', '13', '14', '18', '20', '21', '24', '25',
       '28', '29', '31', '32', '33', '34', '36', '38', '39', '40', '42', '43',
       '45', '47', '48', '49', '51', '55', '56', '58', '60', '61', '62', '65',
       '66', '68', '70', '71', '72', '73', '74', '76', '77', '78', '80', '82',
       '83', '85', '87', '93', '94', '95', '98', '99', '100', '103', '104',
       '106', '107', '108', 'thrombolysis', 'discharge_util',
       'discharge_mrsleq2', 'const'],
      dtype='str')

In [12]:
common_columns=[]

for i in data_columns:
    if i in file_columns:
        common_columns.append(i)

In [13]:
common_columns

['stroke_severity_mild',
 'stroke_severity_moderate',
 'stroke_severity_severe',
 'age_80plus',
 'prior_util',
 'atrial_fibrillation',
 'afib_anticoagulant',
 'onset_during_sleep',
 'precise_onset_known',
 'arrival_to_scan_time',
 '2',
 '3',
 '5',
 '6',
 '7',
 '8',
 '9',
 '11',
 '12',
 '13',
 '14',
 '18',
 '20',
 '21',
 '24',
 '25',
 '28',
 '29',
 '31',
 '32',
 '33',
 '34',
 '36',
 '38',
 '39',
 '40',
 '42',
 '43',
 '45',
 '47',
 '48',
 '49',
 '51',
 '55',
 '56',
 '58',
 '60',
 '61',
 '62',
 '65',
 '66',
 '68',
 '70',
 '71',
 '72',
 '73',
 '74',
 '76',
 '77',
 '78',
 '80',
 '82',
 '83',
 '85',
 '87',
 '93',
 '94',
 '95',
 '98',
 '99',
 '100',
 '103',
 '104',
 '106',
 '107',
 '108']

In [14]:
noise_t = np.random.normal(0, 0.1, patients)

t = np.sum((
    [noise_t] +
    [df_data[col] * df_file.loc[col, 'thrombolysis'] for col in common_columns]
), axis=0)

import math

def sigmoid(x):
    return 1 / (1 + math.exp(-x))

def convert_to_binary(x, stochastic=True):
    p = sigmoid(x)
    if stochastic:
        return np.random.choice([0, 1], 1, p=[1 - p, p])
    else:
        return int(p > 0.5)

t_bin = np.array([convert_to_binary(x) for x in t]).flatten()

In [15]:
df_data['thrombolysis'] = t_bin
df_data

,Stroke severity,stroke_severity_mild,stroke_severity_moderate,stroke_severity_severe,age_80plus,MRS,x_values,prior_util,atrial_fibrillation,afib_anticoagulant,...,107,108,109,110,111,112,113,114,115,thrombolysis
1,25.0,0.0,1.0,0.0,1,4,0.95071,0.42,1,1,...,0,0,0,0,0,0,0,0,0,1
2,13.0,0.0,1.0,0.0,1,3,0.73199,0.62,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9.0,0.0,1.0,0.0,0,0,0.59866,0.95,0,0,...,0,0,0,0,0,0,0,0,0,1
6,2.0,1.0,0.0,0.0,0,0,0.05808,0.95,0,0,...,0,0,0,0,0,0,0,0,0,1
10,2.0,1.0,0.0,0.0,0,0,0.02058,0.95,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,0.0,1.0,0.0,0.0,0,0,0.47111,0.95,0,0,...,0,0,0,0,0,0,0,0,0,0
9993,15.0,0.0,1.0,0.0,1,3,0.81874,0.62,1,0,...,0,0,0,0,0,0,0,0,0,1
9994,3.0,1.0,0.0,0.0,0,0,0.12461,0.95,0,0,...,0,0,0,0,0,0,0,0,0,1
9996,21.0,0.0,1.0,0.0,1,4,0.89751,0.42,1,1,...,0,0,0,0,0,0,0,0,0,1
9997,25.0,0.0,1.0,0.0,1,4,0.94671,0.42,1,0,...,0,0,0,0,0,0,0,0,0,1

In [16]:
out_col="discharge_mrsleq2"

def outcome_calculator(out_col, df_data, df_file):

    np.random.seed(42)
    noise_out = np.random.normal(0, 0.1, patients)

    out = np.sum((
        [noise_out] +
        [df_data[col] * df_file.loc[col, out_col] for col in common_columns]
    ), axis=0) + df_file.loc['const', out_col]

    out_bin = np.array([sigmoid(x) for x in out]).flatten()
    return out_bin

In [17]:
df_data[out_col]=outcome_calculator(out_col, df_data, df_file)
df_data

,Stroke severity,stroke_severity_mild,stroke_severity_moderate,stroke_severity_severe,age_80plus,MRS,x_values,prior_util,atrial_fibrillation,afib_anticoagulant,...,108,109,110,111,112,113,114,115,thrombolysis,discharge_mrsleq2
1,25.0,0.0,1.0,0.0,1,4,0.95071,0.42,1,1,...,0,0,0,0,0,0,0,0,1,0.472152
2,13.0,0.0,1.0,0.0,1,3,0.73199,0.62,0,0,...,0,0,0,0,0,0,0,0,0,0.496989
3,9.0,0.0,1.0,0.0,0,0,0.59866,0.95,0,0,...,0,0,0,0,0,0,0,0,1,0.645936
6,2.0,1.0,0.0,0.0,0,0,0.05808,0.95,0,0,...,0,0,0,0,0,0,0,0,1,0.708848
10,2.0,1.0,0.0,0.0,0,0,0.02058,0.95,0,0,...,0,0,0,0,0,0,0,0,0,0.684843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,0.0,1.0,0.0,0.0,0,0,0.47111,0.95,0,0,...,0,0,0,0,0,0,0,0,0,0.641027
9993,15.0,0.0,1.0,0.0,1,3,0.81874,0.62,1,0,...,0,0,0,0,0,0,0,0,1,0.533004
9994,3.0,1.0,0.0,0.0,0,0,0.12461,0.95,0,0,...,0,0,0,0,0,0,0,0,1,0.672732
9996,21.0,0.0,1.0,0.0,1,4,0.89751,0.42,1,1,...,0,0,0,0,0,0,0,0,1,0.441035
9997,25.0,0.0,1.0,0.0,1,4,0.94671,0.42,1,0,...,0,0,0,0,0,0,0,0,1,0.476472

In [18]:
df_data.to_csv("final_results_11_08.csv")