We have generated data similar to causal test data except it has 10000 samples this time.

In [3]:
import pandas as pd
import numpy as np
import random as rn
import matplotlib.pyplot as plt

In [4]:
num_samples=10000

A- A

In [5]:
np.random.seed(42)
A = np.random.normal(-0.25, 1, num_samples)

B- B

In [6]:
np.random.seed(42)
B = np.random.normal(0.20, 1, num_samples)

C- C

In [7]:
np.random.seed(42)
C = np.random.normal(-0.69, 1, num_samples)

D- D

In [8]:
p = 0.73
np.random.seed(42)
D = np.random.binomial(1, p, num_samples)

E- E

In [9]:
np.random.seed(42)
E= np.random.normal(0.90, 1, num_samples)

Making 1 big dataframe

In [10]:
df=pd.DataFrame([A, B, C, D, E])
df.index=["A","B","C","D","E"]
df=df.T

In [11]:
df.head()

          A         B         C    D         E
0  0.246714  0.696714 -0.193286  1.0  1.396714
1 -0.388264  0.061736 -0.828264  0.0  0.761736
2  0.397689  0.847689 -0.042311  0.0  1.547689
3  1.273030  1.723030  0.833030  1.0  2.423030
4 -0.484153 -0.034153 -0.924153  1.0  0.665847

Adding a yes or no value for treatment


Note: Formula is Treatment= Noise + 0.45A + 0.15E + 1.3D

We had previously used 4.5 but any value of variables above 3 disrupts the flow (based off of a mathematical thing), hence we have reduced it back to under 3

In [12]:
np.random.seed(42)
noise_t = np.random.normal(0, 0.1, num_samples)
t = np.sum([noise_t] + [0.45*A] + [0.15*E] + [1.32*D], axis=0)

In [ ]:
import math

def sigmoid(x):
    return 1 / (1 + math.exp(-x))

def convert_to_binary(x, stochastic=True):
    p = sigmoid(x)
    if stochastic:
        return np.random.choice([0, 1], 1, p=[1 - p, p])
    else:
        return int(p > 0.5)

In [16]:
t_bin = np.array([convert_to_binary(x) for x in t]).flatten()

In [17]:
df['Treatment'] = t_bin

In [18]:
df

             A         B         C    D         E  Treatment
0     0.246714  0.696714 -0.193286  1.0  1.396714          1
1    -0.388264  0.061736 -0.828264  0.0  0.761736          0
2     0.397689  0.847689 -0.042311  0.0  1.547689          0
3     1.273030  1.723030  0.833030  1.0  2.423030          1
4    -0.484153 -0.034153 -0.924153  1.0  0.665847          1
...        ...       ...       ...  ...       ...        ...
9995  1.051102  1.501102  0.611102  0.0  2.201102          1
9996 -2.248345 -1.798345 -2.688345  0.0 -1.098345          1
9997 -0.955317 -0.505317 -1.395317  0.0  0.194683          0
9998  0.245766  0.695766 -0.194234  1.0  1.395766          1
9999  0.394388  0.844388 -0.045612  1.0  1.544388          1

[10000 rows x 6 columns]

Adding Outcome values

Note: The right formula used here is Outcome= Noise + 5*Treatment + 0.33*A + 0.39*E + 0.02*B

We had previously used 3.3 and 3.9 but any value of variables above 3 disrupts the flow (based off of a mathematical thing), hence we have reduced it back to under 3

In [19]:
np.random.seed(42)
noise_out = np.random.normal(0, 0.1, num_samples)
out = np.sum([noise_out] + [5*t_bin] + [0.33*A] + [0.39*E] + [0.02*B*t_bin], axis=0)

In [20]:
noise_out

array([ 0.04967142, -0.01382643,  0.06476885, ..., -0.07053167,
        0.04957656,  0.06443885], shape=(10000,))

In [21]:
df['Outcome'] = out

In [22]:
df

             A         B         C    D         E  Treatment   Outcome
0     0.246714  0.696714 -0.193286  1.0  1.396714          1  5.689740
1    -0.388264  0.061736 -0.828264  0.0  0.761736          0  0.155123
2     0.397689  0.847689 -0.042311  0.0  1.547689          0  0.799605
3     1.273030  1.723030  0.833030  1.0  2.423030          1  6.551845
4    -0.484153 -0.034153 -0.924153  1.0  0.665847          1  5.075811
...        ...       ...       ...  ...       ...        ...       ...
9995  1.051102  1.501102  0.611102  0.0  2.201102          1  6.365426
9996 -2.248345 -1.798345 -2.688345  0.0 -1.098345          1  3.593890
9997 -0.955317 -0.505317 -1.395317  0.0  0.194683          0 -0.309860
9998  0.245766  0.695766 -0.194234  1.0  1.395766          1  5.688943
9999  0.394388  0.844388 -0.045612  1.0  1.544388          1  5.813786

[10000 rows x 7 columns]

In [23]:
df.describe()

,A,B,C,D,E,Treatment,Outcome
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,-0.252136,0.197864,-0.692136,0.740100,0.897864,0.710800,3.826009
std,1.003462,1.003462,1.003462,0.438601,1.003462,0.453414,2.618959
min,-4.172400,-3.722400,-4.612400,0.000000,-3.022400,0.000000,-2.947868
25%,-0.922591,-0.472591,-1.362591,0.000000,0.227409,0.000000,0.791728
50%,-0.252595,0.197405,-0.692595,1.000000,0.897405,1.000000,4.983472
75%,0.421081,0.871081,-0.018919,1.000000,1.571081,1.000000,5.711122
max,3.676238,4.126238,3.236238,1.000000,4.826238,1.000000,8.570540

In [25]:
df.to_csv("final_new_gen_data_continous_10000.csv", index=False)